# -*- coding: UTF-8 -*-
# generated by lino.sphinxcontrib.help_text_builder
from django.utils.translation import gettext_lazy as _

help_texts = {
    "whitewall.lib.whitewall.migrate.Migrator": _(
        """The standard migrator for Whitewall."""
    ),
    "whitewall.lib.users.UserDetail": _(
        """Layout of User Detail in Whitewall."""
    ),
}
